name: love
description: A fun Love Calculator (LoveMeter) Flutter app.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.3.0
  animated_text_kit: ^4.2.2
  confetti: ^0.6.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/heart.json